CREATE TABLE HERO(
    ID INTEGER NOT NULL,
    PRIMARY KEY(ID),

    NAME VARCHAR(255) NOT NULL
);

INSERT INTO HERO (ID, NAME) VALUES (11, 'Mr. Nice');
INSERT INTO HERO (ID, NAME) VALUES (12, 'Narco');
INSERT INTO HERO (ID, NAME) VALUES (13, 'Bombasto');
INSERT INTO HERO (ID, NAME) VALUES (14, 'Celeritas');
INSERT INTO HERO (ID, NAME) VALUES (15, 'Magneta');
INSERT INTO HERO (ID, NAME) VALUES (16, 'RubberMan');
INSERT INTO HERO (ID, NAME) VALUES (17, 'Dynama');
INSERT INTO HERO (ID, NAME) VALUES (18, 'Dr IQ');
INSERT INTO HERO (ID, NAME) VALUES (19, 'Magma');
INSERT INTO HERO (ID, NAME) VALUES (20, 'Tornado');

SELECT * FROM HERO;
