CREATE TABLE RECEITA (
    ID SERIAL NOT NULL,
    PRIMARY KEY(ID),

    NOME VARCHAR(255),
    CALORIAS INTEGER,
    PORCOES INTEGER,
    MODO_PREPARO VARCHAR(255),
);

CREATE TABLE INGREDIENTE(
    ID SERIAL NOT NULL,
    FOREIGN KEY(ID) REFERENCES RECEITA(ID),

    NOME VARCHAR(255) NOT NULL,
);

INSERT INTO RECEITA VALUES (1, 'Brigadeiro', NULL, NULL, NULL);
INSERT INTO RECEITA VALUES (2, 'Bolo de cenoura', NULL, NULL, NULL);
INSERT INTO RECEITA VALUES (3, 'Panqueca', NULL, NULL, NULL);
INSERT INTO RECEITA VALUES (4, 'Pudim', NULL, NULL, NULL);

INSERT INTO INGREDIENTE VALUES (2, '3 ovos');
INSERT INTO INGREDIENTE VALUES (2, '3 cenouras médias raspadas e picadas');
INSERT INTO INGREDIENTE VALUES (2, '1 xícara de óleo');
INSERT INTO INGREDIENTE VALUES (2, '2 xícaras de açúcar');
INSERT INTO INGREDIENTE VALUES (2, '2 xícaras de farinha de trigo');
INSERT INTO INGREDIENTE VALUES (2, '1 colher (sopa) de fermento em pó');
INSERT INTO INGREDIENTE VALUES (2, '1 pitada de sal');

SELECT * FROM RECEITA;
SELECT * FROM INGREDIENTE;
